import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ModalProvider } from "@/hooks/context/useModalContext";
import { AuthProvider } from "./AuthProvider";

const geistSans = localFont( {
  src : "./fonts/GeistVF.woff",
  variable : "--font-geist-sans",
  weight : "100 900",
} );
const geistMono = localFont( {
  src : "./fonts/GeistMonoVF.woff",
  variable : "--font-geist-mono",
  weight : "100 900",
} );

export const metadata : Metadata = {
  title : "Familia App",
  description : "Generated by create next app",
  icons : [
    { rel : 'icon', 'url' : '/favicon.ico' },
    { rel : 'apple-touch-icon', url : '/ios/192.png' }
  ],
  manifest : '/manifest.json',
};

export default function RootLayout( {
                                      children,
                                    } : Readonly<{
  children : React.ReactNode;
}> ) {
  return (
      <html lang="en">
      <body className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }>
      <AuthProvider>
        <ModalProvider>
          { children }
        </ModalProvider>
      </AuthProvider>
      <Toaster />
      </body>
      </html>
  );
}
